name: c_market_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  bloc_concurrency: ^0.2.2
  dart_code_metrics: ^5.7.5
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^14.1.4
  injectable: ^2.1.2
  json_annotation: ^4.9.0
  logger: ^2.3.0
  mocktail: ^1.0.0
  retrofit: ^4.0.1
  stream_transform: ^2.1.0
  intl:
  lottie:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  bootpay: ^4.9.91
  kakao_flutter_sdk_user:
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  shimmer:
  flutter_dotenv:
  firebase_crashlytics: ^4.0.0
  equatable: ^2.0.5


dependency_overrides:
  http: 1.2.1
  uuid: 4.4.0
  image_picker: ^1.1.2

  velocity_x:
  equatable:





dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  velocity_x: 


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/lottie/
    - assets/env/
